#' Individual pathway activity signatures (iPAS)
#'
#' A data set containing the integrative Pathway Activity Signatures (iPAS)
#' The variables are as follows:
#'
#' @format A list with 12 matrices one for each cell line
#' \describe{
#'   \item{columns}{204 KEGG pathways: hsa01521, hsa01522, etc.}
#'   \item{rows}{978 Entrez gene IDs (one for each L1000 probe): 10007, 1001, etc.}
#' }
"iPAS_list"

#' Individual pathway activity signatures (iPAS)
#'
#' @format
#' \describe{
#' }
"iPAS_by_path"

#' KEGG pathway metadata
#'
#' A data set containing metadata for each KEGG pathway.
#'
#' @format A data frame containing KEGG pathway metadata
#' \describe{
#' }
"kegg_meta"

#' Gene metadata for all 978 measured L1000 genes
#'
#' A data set containing metadata for all genes used in iPAS signatures
#'
#' @format A data frame containing Entrez gene IDs, HUGO gene symbols, full
#' gene names, and probe IDs for the L1000 genes
#' \describe{
#' }
"gene_meta"


#' Ensemble pathway weights
#'
#' Weights for signatures from each cell line for each pathway.
#' Weights were determined by logistic regression (with LASSO) using LINCS
#' chemical perturbations of pathway nodes.
#'
#' @format a matrix containing weights
#' \describe{
#' }
"ens_weights_no_intercept"

#' Random RNA-seq data to use for examples
#'
#' This data contained three example input signatures in the form of a matrix
#' (~26K genes x 3 input signatures). The data was generated by randomly
#' permuting log fold-change values from three perturbation experiments.
#'
#' @format a matrix containing three input signatures
#' \describe{
#' }
"rnaseq_input_rand"
